#### 1. Create a null vector of size 10 (★☆☆)

#### 2. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 3. Reverse a vector (first element becomes last) (★☆☆)

#### 4. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 5. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 6. Create a random vector of size 30 and find the mean value (★☆☆)

#### 7. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 9. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 10. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 11. Consider two random arrays A and B, check if they are equal (★★☆)

#### 12. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 13. Given a two dimensional array, how to extract unique rows? (★★★)

#### 13: With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday. Given daily weights, build an array with your average weight per weekend1.

In [ ]:
import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)

#### 14. Make the following 4x7 array that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.



In [ ]:
#  [[ 1  3  5  7  9 11 13]
#  [17 19 21 23 25 27 29]
#  [33 35 37 39 41 43 45]
#  [49 51 53 55 57 59 61]]